#include "src/game/envfx_snow.h"

const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_1___Half_Eyes_v3_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_7___Dead_Eyes_v3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt1),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt2),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt3),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt4),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt5),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt6),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt1_switchboneExpression_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_layer_1),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_1___Half_Eyes_v3_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_face_7___Dead_Eyes_v3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt1),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt2),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt3),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt4),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt5),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt6),
			GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt1_switchboneExpression_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_layer_1),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_1___Half_Eyes_v3_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_7___Dead_Eyes_v3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_bottom_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_Chest_skinned_mesh_layer_1),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_000_offset_001_Chest_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt1),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt2),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt3),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt4),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt5),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt6),
											GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_000_switch_headmodel_opt0_000_switch_001_expressions_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, -77, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_001_RWing_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, 77, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_002_LWing_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_003_LShoulder_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -5, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_004_LArm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -13, -17, mario_000_offset_004_LArm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, 9, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_003_LHand_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_006_Rshoulder_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -5, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_007_RArm_skinned_mesh_layer_1),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -13, 17, mario_000_offset_007_RArm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, -10, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_004_Rhand_mesh_layer_1),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_009_LThigh_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_009_LThigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_010_LLeg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_010_LLeg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_011_LFoot_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_000_offset_011_LFoot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_012_RThigh_skinned_mesh_layer_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_012_RThigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_013_RLeg_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_013_RLeg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_RFoot_skinned_mesh_layer_1),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_RFoot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_metal_v3_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_layer_1_mat_override_metal_v3_0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_4_mat_override_metal_v3_0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_bottom_mesh_layer_1_mat_override_metal_v3_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_001_Chest_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_000_offset_001_Chest_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_metal_v3_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, -77, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_001_RWing_mesh_layer_4_mat_override_metal_v3_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, 77, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_002_LWing_mesh_layer_4_mat_override_metal_v3_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_003_LShoulder_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -5, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_layer_1_mat_override_metal_v3_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_004_LArm_skinned_mesh_layer_1_mat_override_metal_v3_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -13, -17, mario_000_offset_004_LArm_mesh_layer_1_mat_override_metal_v3_0),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, 9, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_003_LHand_mesh_layer_1_mat_override_metal_v3_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_006_Rshoulder_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -5, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_layer_1_mat_override_metal_v3_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_007_RArm_skinned_mesh_layer_1_mat_override_metal_v3_0),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -13, 17, mario_000_offset_007_RArm_mesh_layer_1_mat_override_metal_v3_0),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, -10, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_004_Rhand_mesh_layer_1_mat_override_metal_v3_0),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_009_LThigh_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_009_LThigh_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_010_LLeg_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_010_LLeg_mesh_layer_1_mat_override_metal_v3_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_011_LFoot_skinned_mesh_layer_1_mat_override_metal_v3_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_000_offset_011_LFoot_mesh_layer_1_mat_override_metal_v3_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_012_RThigh_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_012_RThigh_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_013_RLeg_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_013_RLeg_mesh_layer_1_mat_override_metal_v3_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_RFoot_skinned_mesh_layer_1_mat_override_metal_v3_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_RFoot_mesh_layer_1_mat_override_metal_v3_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_Head_NOCAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_switchboneHead_displaylistbone_mesh_layer_1_mat_override_metal_v3_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_LeftHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_LOPEN_000_displaylistOption1_LOPEN_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_OPEN_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_LHandOption1_000_displaylist_003__ROPEN_mesh_layer_1_mat_override_metal_v3_0),
		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_PEACE_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RPEACE_000_displaylist_003__RPEACE_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAP_000_displaylist_003_RCAP_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_WING_Armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_4_mat_override_metal_v3_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_002_switch_option_RCAPHAND_000_displaylist_003_RCAPHAND_mesh_layer_1_mat_override_metal_v3_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_bottom_mesh_layer_1_mat_override_metal_v3_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_001_Chest_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, mario_000_offset_001_Chest_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_Head_mesh_layer_1_mat_override_metal_v3_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_Head_NOCAP_Armature),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, -77, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_001_RWing_mesh_layer_4_mat_override_metal_v3_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, 77, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_002_LWing_mesh_layer_4_mat_override_metal_v3_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_003_LShoulder_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -5, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_layer_1_mat_override_metal_v3_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_004_LArm_skinned_mesh_layer_1_mat_override_metal_v3_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -13, -17, mario_000_offset_004_LArm_mesh_layer_1_mat_override_metal_v3_0),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, 9, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_003_LHand_mesh_layer_1_mat_override_metal_v3_0),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_LeftHand_OPEN_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_006_Rshoulder_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -5, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_layer_1_mat_override_metal_v3_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_007_RArm_skinned_mesh_layer_1_mat_override_metal_v3_0),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, -13, 17, mario_000_offset_007_RArm_mesh_layer_1_mat_override_metal_v3_0),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_FORCE, 65536),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, -10, NULL),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_004_Rhand_mesh_layer_1_mat_override_metal_v3_0),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_OPEN_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_PEACE_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_Armature),
												GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3_jump_mario_RightHand_CAP_WING_Armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_009_LThigh_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_009_LThigh_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_010_LLeg_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_010_LLeg_mesh_layer_1_mat_override_metal_v3_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_011_LFoot_skinned_mesh_layer_1_mat_override_metal_v3_0),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, mario_000_offset_011_LFoot_mesh_layer_1_mat_override_metal_v3_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_012_RThigh_skinned_mesh_layer_1_mat_override_metal_v3_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, mario_000_offset_012_RThigh_mesh_layer_1_mat_override_metal_v3_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_offset_013_RLeg_skinned_mesh_layer_1_mat_override_metal_v3_0),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, mario_000_offset_013_RLeg_mesh_layer_1_mat_override_metal_v3_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_RFoot_skinned_mesh_layer_1_mat_override_metal_v3_0),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_000_displaylist_005_RFoot_mesh_layer_1_mat_override_metal_v3_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_1___Half_Eyes_v3_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_2___Closed_Eyes_v3_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1_mat_override_face_7___Dead_Eyes_v3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_bottom_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_001_Chest_skinned_mesh_layer_1),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, mario_000_offset_001_Chest_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_Head_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt1),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt2),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt3),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt4),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt5),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt6),
																	GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt0_000_switch_headmodel_opt0_000_switch_001_expressions_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, mario_Head_NOCAP_Armature),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, -77, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_001_RWing_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 269, -79, 77, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, mario_000_displaylist_002_LWing_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_003_LShoulder_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -5, 79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_003_LShoulder_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_004_LArm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -13, -17, mario_000_offset_004_LArm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, 9, NULL),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_003_LHand_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, mario_LeftHand_OPEN_Armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_006_Rshoulder_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -5, -79, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_006_Rshoulder_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_007_RArm_skinned_mesh_layer_1),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 67, -13, 17, mario_000_offset_007_RArm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_ANIMATED_PART(LAYER_OPAQUE, 58, 8, -10, NULL),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_004_Rhand_mesh_layer_1),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, mario_RightHand_OPEN_Armature),
																		GEO_BRANCH(1, mario_RightHand_PEACE_Armature),
																		GEO_BRANCH(1, mario_RightHand_CAP_Armature),
																		GEO_BRANCH(1, mario_RightHand_CAP_WING_Armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_009_LThigh_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_009_LThigh_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_010_LLeg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_010_LLeg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_011_LFoot_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, mario_000_offset_011_LFoot_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_012_RThigh_skinned_mesh_layer_1),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mario_000_offset_012_RThigh_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_offset_013_RLeg_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, mario_000_offset_013_RLeg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_RFoot_skinned_mesh_layer_1),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_000_displaylist_005_RFoot_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, mario_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, mario_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, mario_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
